#!/bin/bash
if [ "${DEBUG:-0}" -eq 1 ]; then
    set -x
fi

if [ "$(id -u)" -eq 0 ]; then
    echo "You are root! Please switch user"
    exit 1
fi
if ! type sudo >/dev/null 2>&1; then
    echo "Required sudo command!"
    exit 1
fi
# packages
PACKAGES="
abook
acpi
alsa-utils
build-essential
chromium
conky-all
cryptsetup
curl
debconf
debootstrap
dirmngr
emacs25-lucid
feh
firefox-esr
fonts-font-awesome
fonts-inconsolata
gawk
git
global
gnupg2
gparted
htop
i3
i3lock
ibus-unikey
imagemagick
keepassx
libnotify-bin
mpv
mutt
openvpn
pciutils
policykit-1
ranger
redshift
rxvt-unicode-256color
screen
scrot
silversearcher-ag
socat
strace
task-laptop
tcpdump
tmux
tor
vim
w3m
wicd
wireshark
xbacklight
xdotool
xinit
xinput
xsel
zip
"
sudo apt-get update
IFS=$'\n' sudo apt-get install -y ${PACKAGES}

# configure
## locales
echo "locales locales/default_environment_locale select en_US.UTF-8"         | sudo debconf-set-selections
echo "locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8" | sudo debconf-set-selections
sudo rm -f /etc/locale.gen
sudo dpkg-reconfigure --frontend noninteractive locales

## tzdata
echo 'tzdata  tzdata/Zones/Etc select UTC'          | sudo debconf-set-selections
echo 'tzdata  tzdata/Areas select Asia'             | sudo debconf-set-selections
echo 'tzdata  tzdata/Zones/Asia select Ho_Chi_Minh' | sudo debconf-set-selections
sudo rm -f /etc/localtime /etc/timezone
sudo dpkg-reconfigure --frontend noninteractive tzdata


# dotfiles
wget -O- https://txgvnn.github.io/sh/dots | bash

# i3-config
git clone --depth 2 https://github.com/TxGVNN/i3-config.git ~/.i3
ln -sv ~/.i3/Xresources ~/.Xresources
