#!/bin/bash
# TxGVNN
if [ "${DEBUG:-0}" -eq 1 ]; then
    set -x
fi
OUTPUT="$HOME"
INPUT="https://raw.githubusercontent.com/TxGVNN/dots/master"

msg(){ printf "\e[32m%s\e[0m: %s\n" "$1" "$2";}
msg
banner(){
    echo -e '\e[-1;34m'
    echo -e '  #####        ###   #   #  #   #  #   #'
    echo -e '    #         #      #   #  ##  #  ##  #'
    echo -e '    #    \e[0;31m# #\e[0;34m  # ##   #   #  # # #  # # #'
    echo -e '    #     \e[0;31m#\e[0;34m   #   #   # #   #  ##  #  ##'
    echo -e '    #    \e[0;31m# #\e[0;34m   ###     #    #   #  #   #'
    echo ''
    echo -e '  \e[0;36m[ @author TxGVNN ]\e[0m'
    echo ''
}

# install OUTPUT LINK
install(){
    msg "I" "Install $1"
    if type wget >& /dev/null; then
        wget -qO "$1" "$2"
        return $?
    fi
    if type curl >& /dev/null; then
        curl -sSL -o "$1" "$2"
        return $?
    fi
    echo "Please install wget or curl command!"
    exit 1
}


# install OUTPUT LINK
apply(){
    tmp=$(mktemp -t bakXXXXX -u)
    if grep "TxGVNN" "$1" >& /dev/null ; then
        msg "I" "Skip $1"
        return 0
    fi
    if type wget >& /dev/null; then
        wget -qO "$tmp" "$2"
        cat "$tmp" >> "$1"
        return $?
    fi
    if type curl >& /dev/null; then
        curl -sSL -o "$tmp" "$2"
        cat "$tmp" >> "$1"
        return $?
    fi
    echo "Please install wget or curl command!"
    exit 1
}

# main
banner
install "${OUTPUT}/.screenrc" "${INPUT}/.screenrc"
install "${OUTPUT}/.emacs" "${INPUT}/.emacs"
install "${OUTPUT}/.vimrc" "${INPUT}/.vimrc"
apply "${OUTPUT}/.bashrc" "${INPUT}/.bashrc"
