#!/bin/bash
# TxGVNN
[ "${DEBUG:-0}" -eq 0 ] || set -x

OUTPUT="$HOME"
INPUT="https://raw.githubusercontent.com/TxGVNN/dots/master"

banner(){
    echo ''
    echo '  _____  _     __    _      _      _'
    echo '   | |  \ \_/ / /`_ \ \  / | |\ | | |\ |'
    echo '   |_|  /_/ \ \_\_/  \_\/  |_| \| |_| \|'
    echo ''
    echo '  [ @author TxGVNN ]'
    echo ''
}

# download OUTPUT LINK
download(){
    if type wget >& /dev/null; then
        wget -qO "$1" "$2"
        return $?
    fi
    if type curl >& /dev/null; then
        curl -sSL -o "$1" "$2"
        return $?
    fi
    echo "Please install wget or curl command!"
    exit 1
}

# install OUTPUT LINK
install(){
    if [ -e "$1" ]; then
        echo "W: $1 is exist, backup first"
        cp -v "$1" "$1.$(date +%F@%R.%s)"
    fi

    echo "I: Install $1"
    download "$1" "$2"
}

# install OUTPUT LINK
apply(){
    if grep "TxGVNN" "$1" >& /dev/null ; then
        echo "I: Skip $1"
        return 0
    fi
    tmp=$(mktemp -t bakXXXXX -u)
    echo "O: Apply $1"
    download "$tmp" "$2"
    cat "$tmp" >> "$1"
    return $?
}

# main
banner
install "${OUTPUT}/.screenrc" "${INPUT}/.screenrc"
install "${OUTPUT}/.emacs" "${INPUT}/.emacs"
apply "${OUTPUT}/.bashrc" "${INPUT}/.bashrc"
