#!/bin/bash
PACKAGES="
curl
dropbear
emacs
findutils
gawk
git
global
gnupg
grep
man
openssl
screen
silversearcher-ag
socat
texinfo
tmux
vim
weechat
weechat-python-plugin
zip
"
apt update
IFS=$'\n' apt install -y ${PACKAGES}
