---
title: "Viết ghi chú mỗi ngày làm việc"
date: 2021-03-07T15:07:16+07:00
tags: [emacs]
draft: false
---

Khi còn là sinh viên mình cũng vọc vạch kha khá, kinh nghiệm đọng lại rồi cũng rơi dần nếu không dùng lại, ngay cả những cái đơn giản nhất.
Mình bắt đầu suy nghĩ về việc viết note như là mình hồi xưa đi học để lại các kiến thức trong vở. (Nhưng vở thì mình cũng vứt lâu rồi)


Thế là mình bắt đầu làm nó bài bản hơn. Như 1 cuốn vở ghi chung. Mình cần

- Git cả thư mục viết note đó lên 1 gitlab/github (private)
- Mình sẽ note theo các topic là các folder cho dễ tìm. Kiểu structure 1 chút
- Để tìm 1 note thì mình sẽ tìm theo 2 cách tìm theo file và tìm theo pattern. (dùng find và grep)
- Viết anything có thể note được. Ví dụ mình cho cả đống config về cái gì đó lên luôn, chả sao.
- Hỗ trợ cả encrypt bằng GnuPG
* Bắt đầu

  Từ cái đó mình đã viết ra 1 cái tool là [[https://github.com/txgvnn/gxt][gxt]] (vâng, mình tự sướng bằng tên của mình. Haha)
  Tool này rất tiện cho mình note mọi thứ, và cả share note nhanh chóng nữa. Support `gpg` luôn

* Bây giờ
  Giờ thì ngày nào mình cũng viết vào ~note~ nếu mình ngồi vào máy tính. Mình đưa cả dotfiles của mình vào, nên ngày nào cũng cập nhật. LOL

  Bây giờ <2021-03-07 Sun>, mình đang có:
  - 1914 files
  - 3396 commits
  - Ngày commit đầu tiên là ~2015-09-22~

  Hôì đó mình đang dùng Vim, chưa dùng Emacs.
  Sau này chuyển qua sống trong Emacs thì mình không còn dùng ~gxt~ nhiều trên máy tính của mình nữa.
  Nhưng tool này vẫn hữu dụng trên điện thoại cuả mình. Vì mình sử dụng [[https://termux.com][Termux]] trên điện thoại nên dùng ~gxt~ để tìm kiếm note rất tiện.

* Mình thấy

  Nhảy việc ở vài công ty nhưng mình thấy mọi người THƯỜNG KHÔNG hay viết note, có viết thì cũng chỉ viết tạm vào 1 cái file, hay folder. Rồi họ cài lại máy hay di chuyển công ty thì các tệp đó đều mất hoặc backup vào chỗ nào đó mà chả bao giờ họ mở lại.


  Vì thế với vở ghi chung, mình lấy ví dụ:
  - gặp 1 cái bug, rồi mình note lại. Bữa sau thì cứ thế mà áp dụng.
  - note lại cách chạy 1 cái lệnh gì đó.
  - note lại cả config nào đó, bữa sau đối chiếu
  - note lại cách viết note

  Giờ mình còn có thể xem lại hôì làm ở công ty X, mình đã làm về cái gì. Vì mình đều ghi lại khá khá
